name: Java WebSocket Relay Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix

      - name: Convert `run.sh` to Unix format
        run: dos2unix run.sh

      - name: Make `run.sh` executable
        run: chmod +x run.sh

      - name: Build the project (if applicable)
        run: |
          # Assuming you have a build step; if not, you can skip this.
          mvn clean install || true

      - name: Configure relay
        run: |
          # Ensure configuration files are correctly set up.
          # You can add steps here to modify `relayConfig.ini` or `relays.txt` if needed.

      - name: Run the relay server
        run: |
          # Start the relay server and capture logs.
          nohup ./run.sh > relay.log 2>&1 &
